### ISSUE TITLE
onShow PageLifeCycle 没有效果

### ISSUE THREAD

**Issue by luoei** [hjc22/page_life_cycle#2]
项目是集成到原生

main.dart

`import 'dart:io';
import 'package:extended_image/extended_image.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:qkd_exam_lab_flutter/main_route.dart';
import 'package:qkd_exam_lab_flutter/page/no_route.dart';
import 'package:page_life_cycle/page_life_cycle.dart' show PageNavigatorObserver;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      builder: (c, w) {
        ScreenUtil.instance =
        ScreenUtil(width: 750, height: 1334, allowFontScaling: true)
          ..init(c);
        var data = MediaQuery.of(c);
        return MediaQuery(
          data: data.copyWith(textScaleFactor: 1.0),
          child: w,
        );
      },
      navigatorObservers: [PageNavigatorObserver()],
      initialRoute: "xxx://page/lesson/detail",
      onGenerateRoute: (RouteSettings settings) {
        var routeResult =
        getRouteResult(name: settings.name, arguments: settings.arguments);

        var page = routeResult.widget ?? NoRoute();

        switch (routeResult.pageRouteType) {
          case PageRouteType.material:
            return MaterialPageRoute(settings: settings, builder: (c) => page);
          case PageRouteType.cupertino:
            return CupertinoPageRoute(settings: settings, builder: (c) => page);
          case PageRouteType.transparent:
            return Platform.isIOS
                ? TransparentCupertinoPageRoute(
                settings: settings, builder: (c) => page)
                : TransparentMaterialPageRoute(
                settings: settings, builder: (c) => page);
//            return FFTransparentPageRoute(
//                settings: settings,
//                pageBuilder: (BuildContext context, Animation<double> animation,
//                        Animation<double> secondaryAnimation) =>
//                    page);
          default:
            return Platform.isIOS
                ? CupertinoPageRoute(settings: settings, builder: (c) => page)
                : MaterialPageRoute(settings: settings, builder: (c) => page);
        }
      },
    );
  }
}`

test page:
`

class LessonDetailPage extends StatefulWidget {

  @override
  State<StatefulWidget> createState() => _LessonDetailState();

}

class _LessonDetailState extends State<LessonDetailPage> with AutomaticKeepAliveClientMixin<LessonDetailPage>, PageLifeCycle{

// 路由显示触发
  @override
  void onShow () {
    print("$_TAG page life onShow");
  }

  // 路由隐藏触发
  @override
  void onHide () {
    print("$_TAG page life onHide");
  }
  // app 进入后台，只触发当前路由内绑定的widget
  @override
  void onAppBackground () {
    print("$_TAG page life onAppBackground");
  }
  // app 进入前台，只触发当前路由内绑定的widget
  @override
  void onAppForeground () {
    print("$_TAG page life onAppForeground");
  }

`

这里都没有看到打印日志

**Comment by hjc22** [comment]
问题好了？

**Comment by luoei** [comment]
> 问题好了？

 test page 是原生进入flutter的第一个页面。
在Android上面测试结果：
1、首次进入onShow 未触发。从该页面打开二级页面再返回时会触发。
2、从flutter回到原生时会触发onAppBackground。

**Comment by hjc22** [comment]
首次就是不触发onShow的 首次可用initState

**Comment by hjc22** [comment]
从flutter回到原生时会触发onAppBackground   我修复了下 但是没有办法测试 我没有混合的项目，设置的的首次就是不触发onShow的 首次触发 可用initState就可以了

**Comment by hjc22** [comment]
flutter的前后台就是基于 android 的 onPause onResum来做的，前后台切换，activity切换都会触发

**Comment by luoei** [comment]
> flutter的前后台就是基于 android 的 onPause onResum来做的，前后台切换，activity切换都会触发

已经好了哈

**Comment by hjc22** [comment]
怎么好的

**Comment by luoei** [comment]
> 怎么好的

更新了最新版本。 按照你的建议第一次走 initState ，从flutter回到原生时不会触发onAppBackground了。

**Comment by luoei** [comment]
在Android上面会遇到另外的一个bug，这个有遇到过吗？
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: qingclass.qukeduo.app, PID: 32019
    java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
        at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:227)
        at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:554)
        at g.a.c.b.h.a.a(FlutterRenderer.java:274)
        at g.a.c.b.h.a.a(FlutterRenderer.java:38)
        at g.a.c.b.h.a$b$a.onFrameAvailable(FlutterRenderer.java:145)
        at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:206)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7094)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
    UncaughtException detected: java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
        at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(FlutterJNI.java:227)
        at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(FlutterJNI.java:554)
        at g.a.c.b.h.a.a(FlutterRenderer.java:274)
        at g.a.c.b.h.a.a(FlutterRenderer.java:38)
        at g.a.c.b.h.a$b$a.onFrameAvailable(FlutterRenderer.java:145)
        at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:206)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7094)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)`

**Comment by hjc22** [comment]
我的插件是纯dart代码，没有涉及原生，这个错误应该不是因为这个插件导致的

**Comment by luoei** [comment]
> 我的插件是纯dart代码，没有涉及原生，这个错误应该不是因为这个插件导致的

嗯嗯，我知道是其它插件导致，但是目前没有发现是那个插件。
